CREATE TABLE IF NOT EXISTS jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_key VARCHAR(255) NOT NULL,
  module VARCHAR(50) NOT NULL,
  job_type VARCHAR(100) DEFAULT NULL,
  sheet VARCHAR(100) DEFAULT NULL,
  item VARCHAR(255) DEFAULT NULL,
  lat DECIMAL(10,6) DEFAULT NULL,
  lon DECIMAL(10,6) DEFAULT NULL,
  work_order VARCHAR(100) DEFAULT NULL,
  po VARCHAR(100) DEFAULT NULL,
  unit VARCHAR(20) DEFAULT NULL,
  qty_default DECIMAL(10,2) DEFAULT NULL,
  completed TINYINT(1) NOT NULL DEFAULT 0,
  completed_at DATE DEFAULT NULL,
  invoiced TINYINT(1) NOT NULL DEFAULT 0,
  invoiced_at DATE DEFAULT NULL,
  qty DECIMAL(10,2) DEFAULT NULL,
  current_work TINYINT(1) NOT NULL DEFAULT 0,
  meta TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_job_key (job_key),
  KEY idx_module (module),
  KEY idx_completed (completed),
  KEY idx_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_key VARCHAR(255) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  stored_path TEXT NOT NULL,
  lat DECIMAL(10,6) DEFAULT NULL,
  lon DECIMAL(10,6) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_photos_job_key (job_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
